# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]      # The name of the module we are configuring is "character"
symbol = "âœ"     # The "symbol" segment is being set to "âœ"

[directory]
read_only = "ğŸ”’"

[aws]
disabled = true

[username]
show_always = true
format = "[$user]($style) in "

[git_status]
enabled = true

[hostname]
ssh_only = false
disabled = false
